[book]
authors = ["robertsweetman"]
language = "en"
multilingual = false
src = "src"
title = "Data Engineering"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid-init.js", "mermaid.min.js"]
default-theme = "Rust"
no-section-label = true
